ARG version
FROM almalinux:${version:-9}
ENV course="Devops with AWS" \
    trainer="sivakumar reddy" \
    duration="120hrs"
ARG USERNAME=rakesh
RUN echo "hello user: ${USERNAME}"
CMD ["sleep", "100"]